import numpy as np
import pandas as pd
from hmmlearn.hmm import GaussianHMM
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from typing import Optional, Dict, Any, Union
import logging
import os
import pickle
logging.getLogger("hmmlearn").setLevel(logging.ERROR)
from config import (
    HMM_COMPONENTS, ASSET_MAPPINGS, COMMODITY_TICKERS, YIELD_TICKERS, FRED_TICKERS,
    ATR_MULTIPLIER_FX, ATR_MULTIPLIER_GOLD, MAJORS_FIX_LIST,
    CONFIRMATION_BUFFER, MAJORS_TP_MULTIPLIER, ASSET_N_COMPONENTS, BB_SQUEEZE_THRESHOLD,
    HMM_N_ITER, HMM_COVARS_PRIOR, HMM_MIN_COVAR, FRED_2Y_TICKERS,
    HMM_MODELS_PATH, HMM_USE_PRETRAINED, HMM_FINE_TUNE_ITER_FX, HMM_FINE_TUNE_ITER_COMM
)
from sklearn.metrics import pairwise_distances

def calculate_rsi(series, period=14):
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))

def calculate_atr(df, period=14):
    high_low = df['High'] - df['Low']
    high_close = np.abs(df['High'] - df['Close'].shift())
    low_close = np.abs(df['Low'] - df['Close'].shift())
    ranges = pd.concat([high_low, high_close, low_close], axis=1)
    true_range = np.max(ranges, axis=1)
    return true_range.rolling(window=period).mean()

def calculate_z_score(series, window=100):
    """
    Robust Z-Score calculation using Median Absolute Deviation (MAD).
    Financial returns are fat-tailed; MAD is less sensitive to the very jumps we try to detect.
    """
    if len(series) < 2:
        return 0.0
    returns = series.pct_change().dropna()
    if returns.empty:
        return 0.0
    
    # Use sliding window for local context
    relevant_returns = returns.tail(window)
    median = relevant_returns.median()
    mad = (relevant_returns - median).abs().median()
    
    if mad == 0 or np.isnan(mad):
        return 0.0
        
    current_return = returns.iloc[-1]
    # Robust Z-score: 0.6745 helper makes it comparable to standard Z-score for normal dist
    z_score = 0.6745 * (current_return - median) / mad
    return z_score

def calculate_mahalanobis_distance(df: pd.DataFrame, window: int = 20):
    """
    Multi-dimensional jump detection (Price + Yields + Vol).
    """
    if len(df) < window:
        return 0.0
    
    # Ensure required features exist (Self-sufficient pattern)
    df = df.copy()
    if 'Returns' not in df.columns:
        df['Returns'] = np.log(df['Close'] / df['Close'].shift(1))
    if 'Volatility' not in df.columns:
        df['Volatility'] = df['Returns'].rolling(window=10).std()
    if 'Range' not in df.columns:
        df['Range'] = (df['High'] - df['Low']) / (df['Close'] + 1e-9)
    
    # Select key variables for multi-dim distance
    cols = ['Returns', 'Volatility', 'Range']
    if 'Spec_Feat' in df.columns:
        cols.append('Spec_Feat')
    
    # Drop NaNs generated by rolling
    subset = df[cols].tail(window).dropna()
    if len(subset) < len(cols):
        return 0.0
        
    data = subset.values
    mean = np.mean(data, axis=0)
    try:
        cov = np.cov(data, rowvar=False)
        inv_cov = np.linalg.inv(cov + np.eye(len(cols)) * 1e-6)
    except np.linalg.LinAlgError:
        return 0.0
        
    current = data[-1]
    diff = current - mean
    dist = np.sqrt(np.dot(np.dot(diff, inv_cov), diff.T))
    return float(dist)

def calculate_bb_width(df, period=20):
    sma = df['Close'].rolling(window=period).mean()
    std = df['Close'].rolling(window=period).std()
    upper = sma + (2 * std)
    lower = sma - (2 * std)
    width = (upper - lower) / (sma + 1e-9)
    return width

def prepare_hmm_features(df: pd.DataFrame, ticker: str, macro_data: dict) -> np.ndarray | None:
    """
    Canonical feature engineering for HMM. 
    Maintains exactly 7 features in a fixed order for model compatibility.
    """
    df = df.copy()
    
    # 1. Base Features
    df['Returns'] = np.log(df['Close'] / df['Close'].shift(1))
    df['Range'] = (df['High'] - df['Low']) / (df['Close'] + 1e-9)
    df['Volatility'] = df['Returns'].rolling(window=10).std()
    df['Momentum'] = df['Returns'].rolling(window=5).mean() - df['Returns'].rolling(window=20).mean()
    df['RSI'] = calculate_rsi(df['Close'])
    df['Spec_Feat'] = 0.0 # Default padding
    df['Yield_Spread'] = 0.0 # New 7th Pillar
    
    # 2. Local-Normalization Helper (safe for timezones/units)
    def _norm(frame):
        idx = pd.to_datetime(frame.index)
        if idx.tzinfo is not None: idx = idx.tz_localize(None)
        if hasattr(idx, 'as_unit'): idx = idx.as_unit('ns')
        frame = frame.copy(); frame.index = idx
        return frame

    df = _norm(df)
    price_idx = df.index
    
    # 3. Macro Enrichment
    if ticker in ASSET_MAPPINGS and macro_data:
        mapping = ASSET_MAPPINGS[ticker]
        m_type = mapping['type']
        
        try:
            # A. Specialty Feature (Commodity/DXY Correlations)
            if m_type in ['commodity', 'commodity_inverse', 'macro']:
                key = mapping.get('key') or ('OIL' if 'JPY' not in ticker else 'DXY')
                com_ticker = COMMODITY_TICKERS.get(key) or YIELD_TICKERS.get(key)
                if com_ticker in macro_data and not macro_data[com_ticker].empty:
                    com_df = _norm(macro_data[com_ticker]).reindex(price_idx, method='ffill').bfill()
                    com_ret = np.log(com_df['Close'] / com_df['Close'].shift(1))
                    df['Spec_Feat'] = com_ret.rolling(20).corr(df['Returns']).fillna(0)
            
            # B. Yield Spread Feature (7th Pillar - Momentum of US vs Local yield)
            base_yield = mapping.get('base')
            quote_yield = mapping.get('quote')
            
            if base_yield and quote_yield and macro_data:
                b_ticker = FRED_TICKERS.get(base_yield)
                q_ticker = FRED_TICKERS.get(quote_yield)
                
                if b_ticker in macro_data and q_ticker in macro_data:
                    b_df = _norm(macro_data[b_ticker]).reindex(price_idx, method='ffill').bfill()
                    q_df = _norm(macro_data[q_ticker]).reindex(price_idx, method='ffill').bfill()
                    # Calculate spread momentum over 5 hours
                    spread = b_df['Close'] - q_df['Close']
                    df['Yield_Spread'] = (spread - spread.shift(5)).fillna(0)
        except Exception as e:
            logging.debug(f"Feature enrichment failed for {ticker}: {e}")

    # 4. Finalization
    features_cols = ['Returns', 'Volatility', 'Range', 'Momentum', 'RSI', 'Spec_Feat', 'Yield_Spread']
    for col in features_cols:
        df[col] = df[col].ffill().bfill().fillna(0)
        
    df = df.dropna(subset=features_cols)
    
    # "Goldilocks" Window for live fit
    max_fit_bars = 1200
    if len(df) > max_fit_bars:
        df = df.iloc[-max_fit_bars:]
        
    if df.empty or len(df) < 50:
        return None
        
    return df[features_cols].values # Fixed order

def detect_breakout(df: pd.DataFrame, ticker: Optional[str] = None, macro_data: Optional[Dict[str, Any]] = None, model=None):
    """
    Fits an HMM to detect price regimes and returns standardized results.
    Signature: regime, prob, direction, is_breakout, state_id, atr
    """
    # 1. Shared Feature Engineering
    features = prepare_hmm_features(df, ticker, macro_data)
    if features is None:
        return "None", 0.0, "None", False, -1, 0.0
        
    scaler = StandardScaler()
    features_scaled = scaler.fit_transform(features)
    
    # 2. Asset-Specific HMM Selection
    hmm_model = None
    best_n = ASSET_N_COMPONENTS.get(ticker, ASSET_N_COMPONENTS.get('DEFAULT', 3))
    
    # 2.1 Unified Transfer Learning Layer: Handle passed model or load from disk
    model_data = None

    if isinstance(model, dict) and 'model' in model:
        model_data = model
    elif HMM_USE_PRETRAINED and model is None and ticker:
        model_name = f"{ticker.replace('=X', '').replace('=F', '')}_hmm.pkl"
        model_path = os.path.join(HMM_MODELS_PATH, model_name)
        if os.path.exists(model_path):
            try:
                with open(model_path, 'rb') as f:
                    model_data = pickle.load(f)
            except Exception as e:
                print(f"      [HMM ERROR] Failed to load pre-trained model for {ticker}: {e}")

    if model_data:
        try:
            hmm_model = model_data['model']
            scaler = model_data['scaler']
            features_scaled = scaler.transform(features)
            best_n = hmm_model.n_components
            
            # --- HYBRID TRANSFER LEARNING: Fine-tuning based on Asset Class ---
            is_comm = any(x in ticker for x in ["GC=F", "CL=F"]) if ticker else False
            n_fine_tune = HMM_FINE_TUNE_ITER_COMM if is_comm else HMM_FINE_TUNE_ITER_FX
            
            # Store a backup of the original model in case fine-tuning fails
            pretrained_backup = model_data['model']

            if n_fine_tune > 0:
                # Local adaptation via Baum-Welch
                hmm_model.init_params = ""  # Use loaded params as warm start
                hmm_model.n_iter = n_fine_tune
                hmm_model.fit(features_scaled)

                # STABILITY GUARD: revert to base if NaNs detected post-fit
                if np.isnan(hmm_model.transmat_).any() or np.isnan(hmm_model.means_).any():
                    print(f"      [HMM WARNING] {ticker} fine-tuning produced NaNs. Reverting to base model.")
                    hmm_model = pretrained_backup
            else:
                # FX: Use pure pre-trained weights for maximum stability
                hmm_model = pretrained_backup
        except Exception as e:
            hmm_model = None # Fall back to fresh fit

    # 2.2 Fit HMM with Fallback logic (if not pre-trained or forced)
    if hmm_model is None:
        n_tries = [best_n, 3, 2] if best_n > 3 else [3, 2]
        n_tries = list(dict.fromkeys(n_tries))
        
        for n in n_tries:
            try:
                hmm_model = GaussianHMM(
                    n_components=n, covariance_type="diag",
                    n_iter=HMM_N_ITER, tol=1e-2, random_state=42,
                    covars_prior=HMM_COVARS_PRIOR,
                    min_covar=HMM_MIN_COVAR,
                    init_params="stmc", params="stmc"
                )
                hmm_model.fit(features_scaled)
                if hasattr(hmm_model, 'transmat_'):
                    row_sums = hmm_model.transmat_.sum(axis=1)
                    if not np.allclose(row_sums, 1.0):
                        hmm_model.transmat_ = hmm_model.transmat_ / row_sums[:, np.newaxis]
                break
            except Exception:
                hmm_model = None
                continue
        
        if hmm_model is None:
            # Simple statistical fallback
            atr = calculate_atr(df).iloc[-1]
            return "Consolidation", 0.33, "None", False, -1, float(atr)

    states = hmm_model.predict(features_scaled)
    states = [int(s) for s in states]
    current_state_id = states[-1]

    # 3. Regime Labeling
    state_abs_returns = {i: abs(float(hmm_model.means_[i, 0])) for i in range(hmm_model.n_components)}
    sorted_states = sorted(state_abs_returns.keys(), key=lambda s: state_abs_returns[s])

    state_metrics = {}
    states_arr = np.array(states)
    for i in range(hmm_model.n_components):
        mask = (states_arr == i)
        state_metrics[i] = {
            'ret': float(hmm_model.means_[i, 0]),
            'var': float(features_scaled[mask].var(axis=0).sum()) if np.sum(mask) > 0 else 0.0
        }

    regime_names = ["Consolidation", "Mean Reversion", "Trend Breakout"]
    if hmm_model.n_components == 4: regime_names.append("Trend Breakout")
    
    labels = {}
    for rank, state_id in enumerate(sorted_states):
        labels[state_id] = regime_names[min(rank, len(regime_names) - 1)]

    regime = labels[current_state_id]
    
    # 4. Final Direction and Prob
    avg_ret = state_metrics[current_state_id]['ret']
    direction = "LONG" if avg_ret > 0 else "SHORT"
    
    # ENTROPY GATE: If top probability is < 0.70, the signal is ambiguous "Chop"
    state_probs = hmm_model.predict_proba(features_scaled)
    current_prob = float(state_probs[-1, current_state_id])
    
    if current_prob < 0.70:
        regime = "Consolidation"
        direction = "None"
        # We'll log the veto later in the display logic if needed
        
    # AUD-SPECIFIC CHOP FILTER
    if ticker is not None and 'AUD' in ticker:
        atr_series = calculate_atr(df)
        current_atr = atr_series.iloc[-1]
        rolling_atr = atr_series.rolling(40).mean().iloc[-1]
        if current_atr > 1.4 * rolling_atr:
            regime = "Consolidation"
            direction = "None"

    if regime == "Consolidation": direction = "None"
    
    is_breakout = (regime == "Trend Breakout")
    current_atr = float(calculate_atr(df).iloc[-1])
    
    return regime, current_prob, direction, is_breakout, current_state_id, current_atr

def get_dynamic_exit_levels(regime, price, atr, direction, ticker=None, is_scalp=False):
    """
    State-based Exit Strategy (ATR-keyed):
    - Mean Reversion: Aim for 1.0x ATR profit with 1.5x ATR stop buffer.
    - Trend Breakout: Aim for 3.0x ATR 'Big Move' with tight 1.0x ATR stop.
    - Scalp Mode: Force 1:1 risk/reward using ATR.
    """
    if is_scalp:
        tp_dist = atr * 2.0
        sl_dist = atr * 2.0
    elif regime == "Mean Reversion":
        tp_dist = atr * 1.0
        sl_dist = atr * 2.0  # Increased from 1.5x for robustness
    elif regime == "Trend Breakout":
        # Check if this is a Major inside MAJORS_FIX_LIST
        if ticker in MAJORS_FIX_LIST:
            tp_dist = atr * MAJORS_TP_MULTIPLIER
            sl_dist = atr * 1.2 # Give it room to breathe
        else:
            tp_dist = atr * 2.0
            # Commodities get more room (1.5x ATR) to avoid "noise" stops
            is_commodity = ticker in ['GC=F', 'CL=F'] or ('=F' in str(ticker))
            sl_dist = atr * 1.5 if is_commodity else atr * 1.0
    else:
        return None, None

    if direction == "LONG":
        tp = price + tp_dist
        sl = price - sl_dist
    elif direction == "SHORT":
        tp = price - tp_dist
        sl = price + sl_dist
    else:
        return None, None
        
    return float(tp), float(sl)

def get_trigger_price(df, regime, direction, atr, macro_phase="TRAP_PHASE"):
    """
    1.2 Candle Logic:
    - WIN_PHASE (Macro Aligned): Aggressive entry. Using 0.05 ATR buffer (almost immediate).
    - TRAP_PHASE (Not Aligned): Defensive entry. Requires 0.2 ATR penetration of previous bar.
    """
    if regime != "Trend Breakout" or direction == "None":
        return None
        
    # Get extremes of the signal bar (last closed bar)
    last_high = df['High'].iloc[-1]
    last_low = df['Low'].iloc[-1]
    
    # 1.0 Candle Logic for Win Phase, 1.2 for Trap Phase
    if macro_phase == "WIN_PHASE":
        buffer = 0.05 * atr # Aggressive "Head Start"
    else:
        buffer = CONFIRMATION_BUFFER * atr # Standard 1.2 logic buffer
    
    if direction == "LONG":
        trigger = last_high + buffer
    else:
        trigger = last_low - buffer
        
    return float(trigger)

if __name__ == "__main__":
    pass
