import numpy as np
import pandas as pd
from hmmlearn.hmm import GaussianHMM
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from typing import Optional, Dict, Any, Union
import logging
import os
import pickle
import copy
logging.getLogger("hmmlearn").setLevel(logging.ERROR)
from config import (
    HMM_COMPONENTS, ASSET_MAPPINGS, COMMODITY_TICKERS, YIELD_TICKERS, FRED_TICKERS,
    ATR_MULTIPLIER_FX, ATR_MULTIPLIER_GOLD, MAJORS_FIX_LIST,
    CONFIRMATION_BUFFER, MAJORS_TP_MULTIPLIER, ASSET_N_COMPONENTS, BB_SQUEEZE_THRESHOLD,
    HMM_N_ITER, HMM_COVARS_PRIOR, HMM_MIN_COVAR, FRED_2Y_TICKERS,
    HMM_MODELS_PATH, HMM_USE_PRETRAINED, HMM_FINE_TUNE_ITER_FX, HMM_FINE_TUNE_ITER_COMM,
    ATR_SL_MULTIPLIER, MAJORS_MIN_CONFIDENCE, MINORS_MIN_CONFIDENCE,
    HMM_STATE_DELTA_THRESHOLD, ATR_VOL_CEILING, ATR_CHANDELIER_TRAIL,
    LIQUIDITY_MAP, POLICY_RATES_2026,
    V7_DYNAMIC_SCALING, V7_ROLLING_WINDOW, V7_FORCE_LOOKBACK
)
from sklearn.metrics import pairwise_distances

def calculate_rsi(series, period=14):
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))

def calculate_atr(df, period=14):
    high_low = df['High'] - df['Low']
    high_close = np.abs(df['High'] - df['Close'].shift())
    low_close = np.abs(df['Low'] - df['Close'].shift())
    ranges = pd.concat([high_low, high_close, low_close], axis=1)
    true_range = np.max(ranges, axis=1)
    return true_range.rolling(window=period).mean()

def calculate_synthetic_cvd(df, window=20):
    """
    Synthetic CVD building Intraday Intensity via OHLCV. 
    Returns the Cumulative Volume Delta.
    """
    if 'Volume' not in df.columns:
        return pd.Series(0, index=df.index)
        
    # Scale from -1.0 (Close at Low) to 1.0 (Close at High)
    direction = (2 * ((df['Close'] - df['Low']) / (df['High'] - df['Low'] + 1e-9))) - 1
    delta = df['Volume'] * direction
    return delta.rolling(window=window).sum()

def calculate_z_score(series, window=100):
    """
    Robust Z-Score calculation using Median Absolute Deviation (MAD).
    Financial returns are fat-tailed; MAD is less sensitive to the very jumps we try to detect.
    """
    if len(series) < 2:
        return 0.0
    returns = series.pct_change().dropna()
    if returns.empty:
        return 0.0
    
    # Use sliding window for local context
    relevant_returns = returns.tail(window)
    median = relevant_returns.median()
    mad = (relevant_returns - median).abs().median()
    
    if mad == 0 or np.isnan(mad):
        return 0.0
        
    current_return = returns.iloc[-1]
    # Robust Z-score: 0.6745 helper makes it comparable to standard Z-score for normal dist
    z_score = 0.6745 * (current_return - median) / mad
    return z_score

def calculate_mahalanobis_distance(df: pd.DataFrame, window: int = 20):
    """
    Multi-dimensional jump detection (Price + Yields + Vol).
    """
    if len(df) < window:
        return 0.0
    
    # Ensure required features exist (Self-sufficient pattern)
    df = df.copy()
    if 'Returns' not in df.columns:
        df['Returns'] = np.log(df['Close'] / df['Close'].shift(1))
    if 'Volatility' not in df.columns:
        df['Volatility'] = df['Returns'].rolling(window=10).std()
    if 'Range' not in df.columns:
        df['Range'] = (df['High'] - df['Low']) / (df['Close'] + 1e-9)
    
    # Select key variables for multi-dim distance
    cols = ['Returns', 'Volatility', 'Range']
    if 'Spec_Feat' in df.columns:
        cols.append('Spec_Feat')
    
    # Drop NaNs generated by rolling
    subset = df[cols].tail(window).dropna()
    if len(subset) < len(cols):
        return 0.0
        
    data = subset.values
    mean = np.mean(data, axis=0)
    try:
        cov = np.cov(data, rowvar=False)
        inv_cov = np.linalg.inv(cov + np.eye(len(cols)) * 1e-6)
    except np.linalg.LinAlgError:
        return 0.0
        
    current = data[-1]
    diff = current - mean
    dist = np.sqrt(np.dot(np.dot(diff, inv_cov), diff.T))
    return float(dist)

def calculate_autocorr(series, lag=1, window=30):
    if len(series) < window + lag: return 0.0
    return series.tail(window).autocorr(lag=lag)

def calculate_price_z_score(df, window=20):
    if len(df) < window: return 0.0
    mean = df['Close'].rolling(window=window).mean().iloc[-1]
    std = df['Close'].rolling(window=window).std().iloc[-1]
    if std == 0: return 0.0
    return (df['Close'].iloc[-1] - mean) / std

def calculate_bb_width(df, period=20):
    sma = df['Close'].rolling(window=period).mean()
    std = df['Close'].rolling(window=period).std()
    upper = sma + (2 * std)
    lower = sma - (2 * std)
    width = (upper - lower) / (sma + 1e-9)
    return width

def prepare_hmm_features(df: pd.DataFrame, ticker: str, macro_data: dict) -> np.ndarray | None:
    """
    Canonical feature engineering for HMM. 
    Maintains exactly 7 features in a fixed order for model compatibility.
    """
    df = df.copy()
    
    # 2. Local-Normalization Helper (safe for timezones/units)
    def _norm(frame):
        idx = pd.to_datetime(frame.index)
        if idx.tzinfo is not None: idx = idx.tz_localize(None)
        if hasattr(idx, 'as_unit'): idx = idx.as_unit('ns')
        frame = frame.copy(); frame.index = idx
        return frame

    # 1. Base Leading Technicals (v7.0 Engine Swap)
    df['Returns'] = np.log(df['Close'] / df['Close'].shift(1))
    df['Range'] = (df['High'] - df['Low']) / (df['Close'] + 1e-9)
    
    # A. Volatility Acceleration (Leading)
    vol = df['Returns'].rolling(20).std()
    df['Volatility_Accel'] = (vol / vol.shift(5)) - 1.0 
    
    # B. Returns Acceleration (Leading)
    df['Returns_Accel'] = df['Returns'] - df['Returns'].shift(1)
    
    # C. Force Index Proxy (Leading Money Flow)
    if 'Volume' in df.columns and df['Volume'].sum() > 0:
        df['Force_Index'] = df['Returns'] * df['Volume']
    else:
        df['Force_Index'] = df['Returns'] * (df['High'] - df['Low'])
    
    # D. Range Compression Factor (Leading Breakout Indicator)
    df['Range_Comp'] = df['Range'].rolling(10).mean() / df['Range'].rolling(50).mean()
    
    # E. Defaults for 7-feature symmetry
    df['Spec_Feat'] = 0.0
    df['Yield_Spread'] = 0.0
    
    df = _norm(df)
    price_idx = df.index
    
    # 2. Macro Enrichment (v7.0 Synchronic)
    if ticker in ASSET_MAPPINGS and macro_data:
        mapping = ASSET_MAPPINGS[ticker]
        m_type = mapping['type']
        
        try:
            # A. Specialty Feature (Commodity/DXY Correlations)
            if m_type in ['commodity', 'commodity_inverse', 'macro']:
                key = mapping.get('key') or ('OIL' if 'JPY' not in ticker else 'DXY')
                com_ticker = COMMODITY_TICKERS.get(key) or YIELD_TICKERS.get(key)
                if com_ticker in macro_data and not macro_data[com_ticker].empty:
                    com_df = _norm(macro_data[com_ticker]).reindex(price_idx, method='ffill').bfill()
                    com_ret = np.log(com_df['Close'] / com_df['Close'].shift(1))
                    df['Spec_Feat'] = com_ret.rolling(20).corr(df['Returns']).fillna(0)
            
            # B. Yield Spread Feature (7th Pillar - Momentum of US vs Local yield)
            base_yield = mapping.get('base')
            quote_yield = mapping.get('quote')
            
            if base_yield and quote_yield and macro_data:
                b_ticker = FRED_TICKERS.get(base_yield)
                q_ticker = FRED_TICKERS.get(quote_yield)
                
                if b_ticker in macro_data and q_ticker in macro_data:
                    b_df = _norm(macro_data[b_ticker]).reindex(price_idx, method='ffill').bfill()
                    q_df = _norm(macro_data[q_ticker]).reindex(price_idx, method='ffill').bfill()
                    spread = b_df['Close'] - q_df['Close']
                    df['Yield_Spread'] = (spread - spread.shift(5)).fillna(0)
        except Exception as e:
            logging.debug(f"Feature enrichment failed for {ticker}: {e}")

    # 4. Finalization
    features_cols = ['Returns', 'Volatility_Accel', 'Returns_Accel', 'Force_Index', 'Range_Comp', 'Spec_Feat', 'Yield_Spread']
    for col in features_cols:
        df[col] = df[col].ffill().bfill().fillna(0)
        
    df = df.dropna(subset=features_cols)
    
    # "Goldilocks" Window for live fit
    max_fit_bars = 1200
    if len(df) > max_fit_bars:
        df = df.iloc[-max_fit_bars:]
        
    if df.empty or len(df) < 50:
        return None
        
    return df[features_cols].values # Fixed order

def detect_breakout(df: pd.DataFrame, ticker: Optional[str] = None, macro_data: Optional[Dict[str, Any]] = None, model=None, is_backtest: bool = False):
    """
    Fits an HMM to detect price regimes and returns standardized results.
    Signature: regime, prob, direction, is_breakout, state_id, atr
    """
    # 1. Shared Feature Engineering
    features = prepare_hmm_features(df, ticker, macro_data)
    if features is None:
        return "None", 0.0, "None", False, -1, 0.0
        
    # --- v7.0 ENGINE: DYNAMIC ROLLING SCALING ---
    if V7_DYNAMIC_SCALING:
        scaler = StandardScaler()
        fit_data = features[-V7_ROLLING_WINDOW:] if len(features) > V7_ROLLING_WINDOW else features
        scaler.fit(fit_data)
        features_scaled = scaler.transform(features)
    else:
        scaler = StandardScaler()
        features_scaled = scaler.fit_transform(features)
    
    # 2. Asset-Specific HMM Selection
    hmm_model = None
    best_n = ASSET_N_COMPONENTS.get(ticker, ASSET_N_COMPONENTS.get('DEFAULT', 3))
    
    # 2.1 Unified Transfer Learning Layer: Handle passed model or load from disk
    model_data = None

    if isinstance(model, dict) and 'model' in model:
        model_data = model
    elif HMM_USE_PRETRAINED and model is None and ticker:
        model_name = f"{ticker.replace('=X', '').replace('=F', '')}_hmm.pkl"
        model_path = os.path.join(HMM_MODELS_PATH, model_name)
        if os.path.exists(model_path):
            try:
                with open(model_path, 'rb') as f:
                    model_data = pickle.load(f)
            except Exception as e:
                print(f"      [HMM ERROR] Failed to load pre-trained model for {ticker}: {e}")

    if model_data:
        try:
            hmm_model = model_data['model']
            scaler = model_data['scaler']
            features_scaled = scaler.transform(features)
            best_n = hmm_model.n_components
            
            # --- HYBRID TRANSFER LEARNING: Fine-tuning based on Asset Class ---
            is_comm = any(x in ticker for x in ["GC=F", "CL=F"]) if ticker else False
            n_fine_tune = HMM_FINE_TUNE_ITER_COMM if is_comm else HMM_FINE_TUNE_ITER_FX
            
            # Store a backup of the original model in case fine-tuning fails
            pretrained_backup = copy.deepcopy(model_data['model'])

            if n_fine_tune > 0:
                # Local adaptation via Baum-Welch
                hmm_model.init_params = ""  # Use loaded params as warm start
                hmm_model.n_iter = n_fine_tune
                hmm_model.fit(features_scaled)

                # STABILITY GUARD: revert to base if NaNs detected post-fit
                if (np.isnan(hmm_model.transmat_).any() or 
                    np.isnan(hmm_model.means_).any() or 
                    np.isnan(hmm_model.startprob_).any()):
                    print(f"      [HMM WARNING] {ticker} fine-tuning produced NaNs. Reverting to base model.")
                    hmm_model = pretrained_backup
            else:
                # FX: Use pure pre-trained weights for maximum stability
                hmm_model = pretrained_backup
        except Exception as e:
            hmm_model = None # Fall back to fresh fit

    # 2.2 Fit HMM with Fallback logic (if not pre-trained or forced)
    if hmm_model is None:
        n_tries = [best_n, 3, 2] if best_n > 3 else [3, 2]
        n_tries = list(dict.fromkeys(n_tries))
        
        for n in n_tries:
            try:
                hmm_model = GaussianHMM(
                    n_components=n, covariance_type="diag",
                    n_iter=HMM_N_ITER, tol=1e-2, random_state=42,
                    covars_prior=HMM_COVARS_PRIOR,
                    min_covar=HMM_MIN_COVAR,
                    init_params="stmc", params="stmc"
                )
                hmm_model.fit(features_scaled)
                if hasattr(hmm_model, 'transmat_'):
                    row_sums = hmm_model.transmat_.sum(axis=1)
                    if not np.allclose(row_sums, 1.0):
                        hmm_model.transmat_ = hmm_model.transmat_ / row_sums[:, np.newaxis]
                break
            except Exception:
                hmm_model = None
                continue
        
        if hmm_model is None:
            # Simple statistical fallback
            atr = calculate_atr(df).iloc[-1]
            return "Consolidation", 0.33, "None", False, -1, float(atr)

    states = hmm_model.predict(features_scaled)
    states = [int(s) for s in states]
    current_state_id = states[-1]

    # 3. Regime Labeling
    state_abs_returns = {i: abs(float(hmm_model.means_[i, 0])) for i in range(hmm_model.n_components)}
    sorted_states = sorted(state_abs_returns.keys(), key=lambda s: state_abs_returns[s])

    state_metrics = {}
    states_arr = np.array(states)
    for i in range(hmm_model.n_components):
        mask = (states_arr == i)
        state_metrics[i] = {
            'ret': float(hmm_model.means_[i, 0]),
            'var': float(features_scaled[mask].var(axis=0).sum()) if np.sum(mask) > 0 else 0.0
        }

    regime_names = ["Consolidation", "Mean Reversion", "Trend Breakout"]
    if hmm_model.n_components == 4: regime_names.append("Trend Breakout")
    
    labels = {}
    for rank, state_id in enumerate(sorted_states):
        labels[state_id] = regime_names[min(rank, len(regime_names) - 1)]

    hmm_regime = labels[current_state_id]
    avg_ret = state_metrics[current_state_id]['ret']
    
    # --- v6.1: CARRY-SHIFTED Z-PIVOT (Fix 4) ---
    if hmm_regime == "Mean Reversion":
        z_score = calculate_price_z_score(df, window=20)
        base_c, quote_c = ticker[:3], ticker[3:6]
        base_r = POLICY_RATES_2026.get(base_c, 0)
        quote_r = POLICY_RATES_2026.get(quote_c, 0)
        
        # Favor the carry: join the high-yield gravity
        upper_z = 1.2 if quote_r > (base_r + 1.0) else 1.8 
        lower_z = -1.2 if base_r > (quote_r + 1.0) else -1.8
        
        if z_score > upper_z: direction, regime = "SHORT", "Mean Reversion"
        elif z_score < lower_z: direction, regime = "LONG", "Mean Reversion"
        else: direction, regime = "None", "Consolidation"
    else:
        regime = hmm_regime
        direction = "LONG" if avg_ret > 0 else "SHORT"
    
    # --- v6.1 MATHEMATICAL HARDENING & SESSION FLOOR ---
    state_probs = hmm_model.predict_proba(features_scaled)
    current_probs_vec = state_probs[-1]
    sorted_probs = sorted(current_probs_vec, reverse=True)
    state_delta = float(sorted_probs[0]) - float(sorted_probs[1])
    current_prob = float(sorted_probs[0])
    
    # Confidence Velocity (Momentum Entry)
    prev_prob = float(sorted(state_probs[-2], reverse=True)[0]) if len(state_probs) > 1 else current_prob
    prob_velocity = current_prob - prev_prob
    is_accelerating = (current_prob > 0.55 and prob_velocity > 0.10)

    # A. ENTROPY GATE
    delta_thresh = HMM_STATE_DELTA_THRESHOLD
    if state_delta < delta_thresh: regime, direction = "Consolidation", "None"
        
    # B. SESSION-SPECIFIC CONFIDENCE FLOOR (Fix 3)
    current_hour = df.index[-1].hour
    liq_cfg = LIQUIDITY_MAP.get(ticker, LIQUIDITY_MAP['DEFAULT'])
    is_active = liq_cfg['active'][0] <= current_hour < liq_cfg['active'][1]
    
    # Use Maj/Min specific thresholds for active periods
    active_thresh = MAJORS_MIN_CONFIDENCE if ticker in MAJORS_FIX_LIST else MINORS_MIN_CONFIDENCE
    entropy_threshold = liq_cfg['floor'] if not is_active else active_thresh
    
    if current_prob < entropy_threshold and not is_accelerating:
        regime, direction = "Consolidation", "None"

    # C. AUTOCORR VETO (DISABLED in Unleashed Mode)
    # if regime == "Trend Breakout":
    #     rho1 = calculate_autocorr(df['Returns'], lag=1, window=30)
    #     if rho1 < 0.10: regime, direction = "Consolidation", "None"

    # D. ATR MOMENTUM SAFEGUARD (DISABLED in Unleashed Mode)
    # atr_series = calculate_atr(df)
    # current_atr = float(atr_series.iloc[-1])
    # rolling_atr = float(atr_series.rolling(40).mean().iloc[-1])
    # if current_atr > ATR_VOL_CEILING * rolling_atr: regime, direction = "Consolidation", "None"

    # E. PDE ABSORPTION FILTER (DISABLED in Unleashed Mode)
    # if regime != "Consolidation" and 'Volume' in df.columns:
    #     vol_recent = df['Volume'].tail(10).sum()
    #     if vol_recent > 50: 
    #         price_move = abs(df['Close'].iloc[-1] / df['Close'].iloc[-10] - 1)
    #         pde = (price_move * 1000) / (vol_recent + 1)
    #         if pde < 0.01: regime, direction = "Consolidation", "None"

    # F. HIGH-FREQUENCY MICRO-CVD DIVERGENCE (DISABLED in Unleashed Mode)
    # if not is_backtest and regime != "Consolidation":
    #     from micro_cvd_engine import get_micro_cvd_slope
    #     cvd_slope = get_micro_cvd_slope(ticker)
    #     if direction == "LONG" and cvd_slope < -0.01: regime, direction = "Consolidation", "None"
    #     elif direction == "SHORT" and cvd_slope > 0.01: regime, direction = "Consolidation", "None"

    if regime == "Consolidation": direction = "None"
    
    is_breakout = (regime == "Trend Breakout")
    current_atr = float(calculate_atr(df).iloc[-1])
    
    # --- v7.0 ENGINE: RISK-PARITY SIZING (Fix 3) ---
    kelly_multiplier = 1.0 
    
    # Anti-Arrogance Cap: If HMM is too certain, it's often late.
    if current_prob > 0.92:
        kelly_multiplier = 0.7 
    elif current_prob > 0.80:
        kelly_multiplier = 1.0
    else:
        kelly_multiplier = 0.4 
        
    # Volatility Sizing (Risk Parity)
    atr_series = calculate_atr(df)
    current_atr = float(atr_series.iloc[-1])
    rolling_atr = float(atr_series.rolling(100).mean().iloc[-1])
    vol_adj = rolling_atr / (current_atr + 1e-9)
    kelly_multiplier = kelly_multiplier * min(1.5, max(0.4, vol_adj))
    
    return regime, current_prob, direction, is_breakout, current_state_id, current_atr, float(kelly_multiplier)

def get_dynamic_exit_levels(regime, price, atr, direction, ticker=None, is_scalp=False):
    """
    State-based Exit Strategy (ATR-keyed):
    - Mean Reversion: Aim for 1.0x ATR profit with 1.5x ATR stop buffer.
    - Trend Breakout: Aim for 3.0x ATR 'Big Move' with tight 1.0x ATR stop.
    - Scalp Mode: Force 1:1 risk/reward using ATR.
    """
    if is_scalp:
        tp_dist = atr * 2.0
        sl_dist = atr * 2.0
    elif regime == "Mean Reversion":
        tp_dist = atr * MAJORS_TP_MULTIPLIER
        sl_dist = atr * ATR_SL_MULTIPLIER
    elif regime == "Trend Breakout":
        # PHASE 3 CHANDELIER EXITS: We eliminate the finite TP for Breakouts. 
        # Trades are closed exclusively by the trailing Stop Loss or regime shifts.
        tp_dist = atr * 999.0 
        
        # Initial SL needs room to breathe before the Chandelier pulls it up
        sl_dist = atr * 1.8
    else:
        return None, None

    if direction == "LONG":
        tp = price + tp_dist
        sl = price - sl_dist
    elif direction == "SHORT":
        tp = price - tp_dist
        sl = price + sl_dist
    else:
        return None, None
        
    return float(tp), float(sl)

def get_trigger_price(df, regime, direction, atr, macro_phase="TRAP_PHASE"):
    """
    1.2 Candle Logic:
    - WIN_PHASE (Macro Aligned): Aggressive entry. Using 0.05 ATR buffer (almost immediate).
    - TRAP_PHASE (Not Aligned): Defensive entry. Requires 0.2 ATR penetration of previous bar.
    """
    if regime != "Trend Breakout" or direction == "None":
        return None
        
    # Get extremes of the signal bar (last closed bar)
    last_high = df['High'].iloc[-1]
    last_low = df['Low'].iloc[-1]
    
    # 1.0 Candle Logic for Win Phase, 1.2 for Trap Phase
    if macro_phase == "WIN_PHASE":
        buffer = 0.05 * atr # Aggressive "Head Start"
    else:
        buffer = CONFIRMATION_BUFFER * atr # Standard 1.2 logic buffer
    
    if direction == "LONG":
        trigger = last_high + buffer
    else:
        trigger = last_low - buffer
        
    return float(trigger)

if __name__ == "__main__":
    pass
