import numpy as np
import pandas as pd
from hmmlearn.hmm import GaussianHMM
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from typing import Optional, Dict, Any, Union
from config import (
    HMM_COMPONENTS, ASSET_MAPPINGS, COMMODITY_TICKERS, YIELD_TICKERS, FRED_TICKERS,
    ATR_MULTIPLIER_FX, ATR_MULTIPLIER_GOLD, MAJORS_FIX_LIST,
    CONFIRMATION_BUFFER, MAJORS_TP_MULTIPLIER, ASSET_N_COMPONENTS, BB_SQUEEZE_THRESHOLD,
    HMM_N_ITER, HMM_COVARS_PRIOR, HMM_MIN_COVAR, FRED_2Y_TICKERS
)
from sklearn.metrics import pairwise_distances

def calculate_rsi(series, period=14):
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))

def calculate_atr(df, period=14):
    high_low = df['High'] - df['Low']
    high_close = np.abs(df['High'] - df['Close'].shift())
    low_close = np.abs(df['Low'] - df['Close'].shift())
    ranges = pd.concat([high_low, high_close, low_close], axis=1)
    true_range = np.max(ranges, axis=1)
    return true_range.rolling(window=period).mean()

def calculate_z_score(series, window=100):
    """
    Robust Z-Score calculation using Median Absolute Deviation (MAD).
    Financial returns are fat-tailed; MAD is less sensitive to the very jumps we try to detect.
    """
    if len(series) < 2:
        return 0.0
    returns = series.pct_change().dropna()
    if returns.empty:
        return 0.0
    
    # Use sliding window for local context
    relevant_returns = returns.tail(window)
    median = relevant_returns.median()
    mad = (relevant_returns - median).abs().median()
    
    if mad == 0 or np.isnan(mad):
        return 0.0
        
    current_return = returns.iloc[-1]
    # Robust Z-score: 0.6745 helper makes it comparable to standard Z-score for normal dist
    z_score = 0.6745 * (current_return - median) / mad
    return z_score

def calculate_mahalanobis_distance(df: pd.DataFrame, window: int = 20):
    """
    Multi-dimensional jump detection (Price + Yields + Vol).
    """
    if len(df) < window:
        return 0.0
    
    # Ensure required features exist (Self-sufficient pattern)
    df = df.copy()
    if 'Returns' not in df.columns:
        df['Returns'] = np.log(df['Close'] / df['Close'].shift(1))
    if 'Volatility' not in df.columns:
        df['Volatility'] = df['Returns'].rolling(window=10).std()
    if 'Range' not in df.columns:
        df['Range'] = (df['High'] - df['Low']) / (df['Close'] + 1e-9)
    
    # Select key variables for multi-dim distance
    cols = ['Returns', 'Volatility', 'Range']
    if 'Spec_Feat' in df.columns:
        cols.append('Spec_Feat')
    
    # Drop NaNs generated by rolling
    subset = df[cols].tail(window).dropna()
    if len(subset) < len(cols):
        return 0.0
        
    data = subset.values
    mean = np.mean(data, axis=0)
    try:
        cov = np.cov(data, rowvar=False)
        inv_cov = np.linalg.inv(cov + np.eye(len(cols)) * 1e-6)
    except np.linalg.LinAlgError:
        return 0.0
        
    current = data[-1]
    diff = current - mean
    dist = np.sqrt(np.dot(np.dot(diff, inv_cov), diff.T))
    return float(dist)

def calculate_bb_width(df, period=20):
    sma = df['Close'].rolling(window=period).mean()
    std = df['Close'].rolling(window=period).std()
    upper = sma + (2 * std)
    lower = sma - (2 * std)
    width = (upper - lower) / (sma + 1e-9)
    return width

def detect_breakout(df: pd.DataFrame, ticker: Optional[str] = None, macro_data: Optional[Dict[str, Any]] = None, model=None):
    """
    Fits an HMM to detect price regimes using BIC for optimal state selection.
    Features: Returns, Volatility, Range, Momentum, RSI, Vol/Vol Ratio.
    Asset-Specific Extras: Commodity Correlation or Yield levels.
    """
    df = df.copy()
    
    # 1. Feature Engineering
    df['Returns'] = np.log(df['Close'] / df['Close'].shift(1))
    df['Range'] = (df['High'] - df['Low']) / df['Close']
    df['Volatility'] = df['Returns'].rolling(window=10).std()
    df['Momentum'] = df['Returns'].rolling(window=5).mean() - df['Returns'].rolling(window=20).mean()
    df['RSI'] = calculate_rsi(df['Close'])
    df['ATR'] = calculate_atr(df)
    df['ATR_Norm'] = df['ATR'] / df['Close']
    
    features_cols = ['Returns', 'Volatility', 'Range', 'Momentum', 'RSI']
    
    # Efficiency Equilibrium: SmartRatio for Majors
    if ticker in ["EURUSD=X", "GBPUSD=X"] and 'Volume' in df.columns:
        df['SmartRatio'] = df['Volume'] / (df['ATR'] + 1e-9)
        features_cols.append('SmartRatio')

    # 1.1 Asset-Specific Features
    if ticker in ASSET_MAPPINGS and macro_data:
        mapping = ASSET_MAPPINGS[ticker]
        m_type = mapping['type']
        m_key = mapping.get('key') # Use .get() as 'macro' doesn't have a 'key'
        
        # "Clean-Join" Pattern: Standardize and align
        price_idx = df.index.tz_localize(None) if df.index.tz else df.index
        df.index = price_idx
        
        if m_type == 'commodity':
            com_ticker = COMMODITY_TICKERS.get(m_key)
            if com_ticker in macro_data:
                com_df = macro_data[com_ticker].copy()
                com_df.index = com_df.index.tz_localize(None) if com_df.index.tz else com_df.index
                
                # Align and map daily/sparse data to high-freq index
                com_df_aligned = com_df.reindex(price_idx, method='ffill').bfill()
                
                # Rolling correlation with commodity returns
                com_ret = np.log(com_df_aligned['Close'] / com_df_aligned['Close'].shift(1))
                df['Spec_Feat'] = com_ret.rolling(20).corr(df['Returns'])
                features_cols.append('Spec_Feat')
                
        elif m_type == 'yield':
            yield_ticker = YIELD_TICKERS.get(m_key)
            if yield_ticker in macro_data:
                yield_df = macro_data[yield_ticker].copy()
                yield_df.index = yield_df.index.tz_localize(None) if yield_df.index.tz else yield_df.index
                
                # Align and carry yields into FX session gaps
                yield_df_aligned = yield_df.reindex(price_idx, method='ffill').bfill()
                
                # Include absolute yield level
                df['Spec_Feat'] = yield_df_aligned['Close'] 
                features_cols.append('Spec_Feat')

        elif m_type == 'macro':
            base_key = mapping['base']
            quote_key = mapping['quote']
            # Search both Yahoo and FRED sources
            base_ticker = YIELD_TICKERS.get(base_key) or FRED_TICKERS.get(base_key)
            quote_ticker = YIELD_TICKERS.get(quote_key) or FRED_TICKERS.get(quote_key)
            dxy_ticker = YIELD_TICKERS.get('DXY')
            
            if base_ticker in macro_data and quote_ticker in macro_data and not macro_data[base_ticker].empty and not macro_data[quote_ticker].empty:
                base_df = macro_data[base_ticker].copy()
                quote_df = macro_data[quote_ticker].copy()
                
                base_df.index = base_df.index.tz_localize(None) if base_df.index.tz else base_df.index
                quote_df.index = quote_df.index.tz_localize(None) if quote_df.index.tz else quote_df.index
                
                # Align both and calc spread
                base_aligned = base_df.reindex(price_idx, method='ffill').bfill()
                quote_aligned = quote_df.reindex(price_idx, method='ffill').bfill()
                
                df['Spec_Feat'] = base_aligned['Close'] - quote_aligned['Close']
                features_cols.append('Spec_Feat')
                
                # --- EFFICIENCY EQUILIBRIUM: 2s10s spread ROC ---
                is_eur = ticker.startswith("EUR") if ticker else False
                two_y_key = 'GER2Y' if is_eur else 'UK2Y'
                two_y_ticker = FRED_2Y_TICKERS.get(two_y_key)
                
                if two_y_ticker in macro_data and not macro_data[two_y_ticker].empty:
                    two_y_df = macro_data[two_y_ticker].copy()
                    two_y_df.index = two_y_df.index.tz_localize(None) if two_y_df.index.tz else two_y_df.index
                    two_y_aligned = two_y_df.reindex(price_idx, method='ffill').bfill()
                    
                    # Domestic 2s10s spread
                    spread_2s10s = base_aligned['Close'] - two_y_aligned['Close']
                    # ROC of the spread (5-bar rolling change)
                    df['Yield_ROC'] = spread_2s10s.diff(5)
                    df['Yield_ROC'] = df['Yield_ROC'].fillna(0)
                    features_cols.append('Yield_ROC')
            elif dxy_ticker in macro_data and not macro_data[dxy_ticker].empty:
                # Fallback to DXY if primary yield spread is missing
                dxy_df = macro_data[dxy_ticker].copy()
                dxy_df.index = dxy_df.index.tz_localize(None) if dxy_df.index.tz else dxy_df.index
                dxy_aligned = dxy_df.reindex(price_idx, method='ffill').bfill()
                # We use -DXY as the feature because stronger DXY -> lower EURUSD/GBPUSD
                df['Spec_Feat'] = -dxy_aligned['Close']
                features_cols.append('Spec_Feat')

    df = df.dropna()
    
    # 1.2 "Goldilocks" Window: Use 1,000 - 1,200 bars to avoid overfitting
    # 70 days of 1h data is ~1680 bars, we trim to most recent 1200 for fitting
    max_fit_bars = 1200
    if len(df) > max_fit_bars:
        df = df.iloc[-max_fit_bars:]
        
    features = df[features_cols].values
    scaler = StandardScaler()
    features_scaled = scaler.fit_transform(features)
    
    # 2. Asset-Specific HMM Selection
    best_n = ASSET_N_COMPONENTS.get(ticker, ASSET_N_COMPONENTS.get('DEFAULT', 3))
    
    # 2.1 Fit HMM with Fallback logic
    if model is None:
        n_tries = [best_n, 3, 2] if best_n > 3 else [3, 2]
        # Remove duplicates while preserving order
        n_tries = list(dict.fromkeys(n_tries))
        
        last_exception = None
        for n in n_tries:
            try:
                model = GaussianHMM(
                    n_components=n, covariance_type="diag",
                    n_iter=HMM_N_ITER, tol=1e-2, random_state=42,
                    covars_prior=HMM_COVARS_PRIOR,
                    min_covar=HMM_MIN_COVAR,
                    init_params="stmc", params="stmc" # Ensure robust initialization
                )
                model.fit(features_scaled)
                
                # Validation: Check for invalid transition matrices (zero-sum rows)
                if hasattr(model, 'transmat_'):
                    row_sums = model.transmat_.sum(axis=1)
                    if not np.allclose(row_sums, 1.0):
                        model = None
                        raise ValueError("Invalid transmat: rows do not sum to 1")
                
                best_n = n # Update best_n in case we fell back
                break
            except Exception as e:
                model = None
                last_exception = e
                continue
        
        if model is None or not hasattr(model, 'monitor_'):
            print(f"      [HMM WARNING] {ticker} HMM failed! Using simple statistical fallback.")
            avg_vol = float(df['Volatility'].mean())
            curr_vol = float(df['Volatility'].iloc[-1])
            avg_ret = float(df['Returns'].mean())
            
            # More descriptive regime fallback
            if curr_vol > avg_vol * 1.5:
                regime = "Trend Breakout"
            elif curr_vol > avg_vol:
                regime = "Mean Reversion"
            else:
                regime = "Consolidation"
                
            direction = "LONG" if avg_ret > 0 else "SHORT"
            current_atr = float(df['ATR'].iloc[-1])
            
            print(f"      [FALLBACK] Regime: {regime} | Direction: {direction}")
            return (regime == "Trend Breakout"), direction, regime, 0, current_atr, 1.0
    else:
        best_n = model.n_components

    states = model.predict(features_scaled)
    # Convert to plain Python ints throughout to avoid numpy hashability issues
    states = [int(s) for s in states]
    current_state_id = states[-1]

    # 3. Regime Labeling via KMeans "Hard Boundary" approach
    # Run KMeans on the full feature space to find 3 decisive cluster centers
    km = KMeans(n_clusters=best_n, random_state=42, n_init=10)
    km.fit(features_scaled)
    # Assign each HMM state to the nearest KMeans cluster center
    # by matching HMM means_ to KMeans centers
    dist_matrix = pairwise_distances(model.means_, km.cluster_centers_)
    hmm_to_km = np.argmin(dist_matrix, axis=1)   # which KMeans cluster each HMM state maps to

    # Rank KMeans clusters by total variance in feature space → activity level
    km_variances = np.zeros(best_n)
    km_labels = km.predict(features_scaled)
    for k in range(best_n):
        mask = (km_labels == k)
        if np.sum(mask) > 0:
            km_variances[k] = features_scaled[mask].var(axis=0).sum()

    # Sort KMeans clusters: low variance = Consolidation, high = Trend Breakout
    km_sorted = np.argsort(km_variances)   # [lowest_var_cluster, ..., highest]
    
    regime_names = ["Consolidation", "Mean Reversion", "Trend Breakout"]
    if best_n == 4 and ticker == 'GC=F':
        regime_names.append("Safe Haven Spike")
        
    km_rank = {int(km_sorted[i]): regime_names[i] for i in range(len(km_sorted))}

    # Build final label map: HMM state → regime string (via KMeans cluster)
    labels = {int(i): km_rank[int(hmm_to_km[i])] for i in range(best_n)}

    # Build per-state return metrics for direction and variance
    state_metrics = {}
    states_arr = np.array(states)
    for i in range(best_n):
        mask = (states_arr == i)
        if np.sum(mask) > 0:
            state_metrics[i] = {
                'ret': float(df['Returns'].values[mask].mean()),
                'var': float(features_scaled[mask].var(axis=0).sum())
            }
        else:
            state_metrics[i] = {'ret': 0.0, 'var': 999.0}

    # Final Patch: If crucial labels are missing, force them based on state variances
    for needed in ["Consolidation", "Trend Breakout"]:
        if needed not in set(labels.values()):
            if needed == "Consolidation":
                # State with absolute lowest variance
                target_id = min(state_metrics.keys(), key=lambda k: state_metrics[k]['var'])
            else:
                # State with absolute highest variance
                target_id = max(state_metrics.keys(), key=lambda k: state_metrics[k]['var'])
            labels[target_id] = needed

    regime = labels[current_state_id]

    # 4. Statistical Separation Guard — dynamic ATR-based
    # Only reject a Trend Breakout if its return separation from Consolidation is too small
    if regime == "Trend Breakout":
        cons_id = [k for k, v in labels.items() if v == "Consolidation"][0]
        break_id = current_state_id
        mu_cons = state_metrics[cons_id]['ret']
        mu_break = state_metrics[break_id]['ret']
        current_atr_norm = float(df['ATR_Norm'].iloc[-1])
        
        # EURUSD Volatility Squeeze Filter
        if ticker == 'EURUSD=X':
            bb_width = calculate_bb_width(df).iloc[-1]
            if bb_width > BB_SQUEEZE_THRESHOLD:
                regime = "Consolidation"
        
        # --- VOLUME-VOLATILITY DIVERGENCE FILTER (Majors) ---
        if ticker in ["EURUSD=X", "GBPUSD=X"] and regime == "Trend Breakout":
            if 'Volume' in df.columns:
                avg_vol = df['Volume'].rolling(window=10).mean().iloc[-1]
                curr_vol = df['Volume'].iloc[-1]
                if curr_vol < avg_vol * 0.9: # Loosened from 0.8
                     regime = "Consolidation"
        
        # Determine multiplier (K) based on asset type
        if regime == "Trend Breakout": # Check again if not filtered by BB
            is_commodity = ticker in ['GC=F', 'CL=F'] or ('=F' in str(ticker))
            k = ATR_MULTIPLIER_GOLD if is_commodity else ATR_MULTIPLIER_FX
            
            mu_diff_threshold = current_atr_norm * k
            if abs(mu_break - mu_cons) < mu_diff_threshold:
                regime = "Consolidation"

    is_breakout = (regime == "Trend Breakout")
    direction = "None"
    if is_breakout or regime == "Mean Reversion":
        avg_ret = state_metrics[current_state_id]['ret']
        direction = "LONG" if avg_ret > 0 else "SHORT"
    
    current_atr = float(df['ATR'].iloc[-1])
    # Get the posterior probability of the current state
    state_probs = model.predict_proba(features_scaled)
    current_prob = float(state_probs[-1, current_state_id])
    
    return is_breakout, direction, regime, current_state_id, current_atr, current_prob

def get_dynamic_exit_levels(regime, price, atr, direction, ticker=None, is_scalp=False):
    """
    State-based Exit Strategy (ATR-keyed):
    - Mean Reversion: Aim for 1.0x ATR profit with 1.5x ATR stop buffer.
    - Trend Breakout: Aim for 3.0x ATR 'Big Move' with tight 1.0x ATR stop.
    - Scalp Mode: Force 1:1 risk/reward using ATR.
    """
    if is_scalp:
        tp_dist = atr * 2.0
        sl_dist = atr * 2.0
    elif regime == "Mean Reversion":
        tp_dist = atr * 1.0
        sl_dist = atr * 2.0  # Increased from 1.5x for robustness
    elif regime == "Trend Breakout":
        # Check if this is a Major inside MAJORS_FIX_LIST
        if ticker in MAJORS_FIX_LIST:
            tp_dist = atr * MAJORS_TP_MULTIPLIER
            sl_dist = atr * 1.2 # Give it room to breathe
        else:
            tp_dist = atr * 2.0
            # Commodities get more room (1.5x ATR) to avoid "noise" stops
            is_commodity = ticker in ['GC=F', 'CL=F'] or ('=F' in str(ticker))
            sl_dist = atr * 1.5 if is_commodity else atr * 1.0
    else:
        return None, None

    if direction == "LONG":
        tp = price + tp_dist
        sl = price - sl_dist
    elif direction == "SHORT":
        tp = price - tp_dist
        sl = price + sl_dist
    else:
        return None, None
        
    return float(tp), float(sl)

def get_trigger_price(df, regime, direction, atr, macro_phase="TRAP_PHASE"):
    """
    1.2 Candle Logic:
    - WIN_PHASE (Macro Aligned): Aggressive entry. Using 0.05 ATR buffer (almost immediate).
    - TRAP_PHASE (Not Aligned): Defensive entry. Requires 0.2 ATR penetration of previous bar.
    """
    if regime != "Trend Breakout" or direction == "None":
        return None
        
    # Get extremes of the signal bar (last closed bar)
    last_high = df['High'].iloc[-1]
    last_low = df['Low'].iloc[-1]
    
    # 1.0 Candle Logic for Win Phase, 1.2 for Trap Phase
    if macro_phase == "WIN_PHASE":
        buffer = 0.05 * atr # Aggressive "Head Start"
    else:
        buffer = CONFIRMATION_BUFFER * atr # Standard 1.2 logic buffer
    
    if direction == "LONG":
        trigger = last_high + buffer
    else:
        trigger = last_low - buffer
        
    return float(trigger)

if __name__ == "__main__":
    pass
